default: &default
  host: http://badgecraft-abril.herokuapp.com

development:
  <<: *default

dev:
  <<: *default

qa:
  <<: *default

test:
  <<: *default

stage:
  <<: *default

production:
  <<: *default
