require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BadgeAssertionsController do

  # This should return the minimal set of attributes required to create a valid
  # BadgeAssertion. As you add validations to BadgeAssertion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "badge" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BadgeAssertionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all badge_assertions as @badge_assertions" do
      badge_assertion = BadgeAssertion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:badge_assertions).should eq([badge_assertion])
    end
  end

  describe "GET show" do
    it "assigns the requested badge_assertion as @badge_assertion" do
      badge_assertion = BadgeAssertion.create! valid_attributes
      get :show, {:id => badge_assertion.to_param}, valid_session
      assigns(:badge_assertion).should eq(badge_assertion)
    end
  end

  describe "GET new" do
    it "assigns a new badge_assertion as @badge_assertion" do
      get :new, {}, valid_session
      assigns(:badge_assertion).should be_a_new(BadgeAssertion)
    end
  end

  describe "GET edit" do
    it "assigns the requested badge_assertion as @badge_assertion" do
      badge_assertion = BadgeAssertion.create! valid_attributes
      get :edit, {:id => badge_assertion.to_param}, valid_session
      assigns(:badge_assertion).should eq(badge_assertion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BadgeAssertion" do
        expect {
          post :create, {:badge_assertion => valid_attributes}, valid_session
        }.to change(BadgeAssertion, :count).by(1)
      end

      it "assigns a newly created badge_assertion as @badge_assertion" do
        post :create, {:badge_assertion => valid_attributes}, valid_session
        assigns(:badge_assertion).should be_a(BadgeAssertion)
        assigns(:badge_assertion).should be_persisted
      end

      it "redirects to the created badge_assertion" do
        post :create, {:badge_assertion => valid_attributes}, valid_session
        response.should redirect_to(BadgeAssertion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved badge_assertion as @badge_assertion" do
        # Trigger the behavior that occurs when invalid params are submitted
        BadgeAssertion.any_instance.stub(:save).and_return(false)
        post :create, {:badge_assertion => { "badge" => "invalid value" }}, valid_session
        assigns(:badge_assertion).should be_a_new(BadgeAssertion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BadgeAssertion.any_instance.stub(:save).and_return(false)
        post :create, {:badge_assertion => { "badge" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested badge_assertion" do
        badge_assertion = BadgeAssertion.create! valid_attributes
        # Assuming there are no other badge_assertions in the database, this
        # specifies that the BadgeAssertion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BadgeAssertion.any_instance.should_receive(:update).with({ "badge" => "" })
        put :update, {:id => badge_assertion.to_param, :badge_assertion => { "badge" => "" }}, valid_session
      end

      it "assigns the requested badge_assertion as @badge_assertion" do
        badge_assertion = BadgeAssertion.create! valid_attributes
        put :update, {:id => badge_assertion.to_param, :badge_assertion => valid_attributes}, valid_session
        assigns(:badge_assertion).should eq(badge_assertion)
      end

      it "redirects to the badge_assertion" do
        badge_assertion = BadgeAssertion.create! valid_attributes
        put :update, {:id => badge_assertion.to_param, :badge_assertion => valid_attributes}, valid_session
        response.should redirect_to(badge_assertion)
      end
    end

    describe "with invalid params" do
      it "assigns the badge_assertion as @badge_assertion" do
        badge_assertion = BadgeAssertion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BadgeAssertion.any_instance.stub(:save).and_return(false)
        put :update, {:id => badge_assertion.to_param, :badge_assertion => { "badge" => "invalid value" }}, valid_session
        assigns(:badge_assertion).should eq(badge_assertion)
      end

      it "re-renders the 'edit' template" do
        badge_assertion = BadgeAssertion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BadgeAssertion.any_instance.stub(:save).and_return(false)
        put :update, {:id => badge_assertion.to_param, :badge_assertion => { "badge" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested badge_assertion" do
      badge_assertion = BadgeAssertion.create! valid_attributes
      expect {
        delete :destroy, {:id => badge_assertion.to_param}, valid_session
      }.to change(BadgeAssertion, :count).by(-1)
    end

    it "redirects to the badge_assertions list" do
      badge_assertion = BadgeAssertion.create! valid_attributes
      delete :destroy, {:id => badge_assertion.to_param}, valid_session
      response.should redirect_to(badge_assertions_url)
    end
  end

end
